version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-vacancies
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    ports:
      - '8010:8080'
    volumes:
      - .:/code
    networks:
      - app-network
networks:
  app-network:
    driver: bridge